# Generated by Django 4.0.3 on 2022-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSEMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamTitle', models.CharField(max_length=95)),
                ('MaxMarks', models.IntegerField()),
                ('ScoredMarks', models.IntegerField()),
                ('Result', models.CharField(max_length=15)),
            ],
        ),
    ]
