# Generated by Django 4.0.3 on 2022-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECEMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamTitle', models.CharField(max_length=95)),
                ('MaxMarks', models.IntegerField()),
                ('ScoredMarks', models.IntegerField()),
                ('Result', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ENGMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamTitle', models.CharField(max_length=95)),
                ('MaxMarks', models.IntegerField()),
                ('ScoredMarks', models.IntegerField()),
                ('Result', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MATMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamTitle', models.CharField(max_length=95)),
                ('MaxMarks', models.IntegerField()),
                ('ScoredMarks', models.IntegerField()),
                ('Result', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PHYMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamTitle', models.CharField(max_length=95)),
                ('MaxMarks', models.IntegerField()),
                ('ScoredMarks', models.IntegerField()),
                ('Result', models.CharField(max_length=15)),
            ],
        ),
    ]
